version: '3.4'
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    restart: always
    links: 
      - hhvm
  hhvm:
    network_mode: host
    build:
      context: ./docker/hhvm
    volumes:
      - .:/var/www/html
      - ./docker/hhvm/hh.conf:/etc/hh.conf
      - ./docker/hhvm/php.ini:/etc/hhvm/php.ini
      - ./docker/hhvm/server.ini:/etc/hhvm/server.ini
    command: hhvm --mode server -vServer.AllowRunAsRoot=1 
    restart: always
